### ISSUE TITLE
Sigabrt  at  src/main/listen.c[2693] ver. 3.0.9

### ISSUE THREAD

**Issue by paja2** [FreeRADIUS/freeradius-server#1129]
Hi 
I'm using "FreeRADIUS Version 3.0.9, for host x86_64-pc-linux-gnu, built on Jul  4 2015 at 13:30:43" compiled from git at debian linux. After cca 1 hour of real trafic running server goin down with:

```
... cleaning up socket auth from client (195.113.XXX.XXX, 56490) -> (*, 2083, virtual-server=default)
ASSERT FAILED src/main/listen.c[2693]: !sock->packet || (talloc_parent(sock->packet) == sock)
RAISING SIGNAL: Aborted

Program received signal SIGABRT, Aborted.
```

GDB info:

```
(gdb) bt 
#0  0x00007ffff649a79b in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:37
#1  0x00007ffff7963337 in fr_fault (sig=6) at src/lib/debug.c:644
#2  0x00007ffff7bc16e1 in rad_assert_fail (file=0x45877c "src/main/listen.c", line=2693, expr=0x45bd68 "!sock->packet || (talloc_parent(sock->packet) == sock)") at src/main/util.c:556
#3  0x000000000041feae in _listener_free (this=0x998280) at src/main/listen.c:2693
#4  0x00007ffff6ee25f3 in _talloc_free () from /usr/lib/x86_64-linux-gnu/libtalloc.so.2
#5  0x0000000000442eb7 in listener_free_cb (ctx=0x998280) at src/main/process.c:4607
#6  0x00007ffff79891c1 in fr_event_run (el=0x8dbcb0, when=0x7fffffffe4c0) at src/lib/event.c:309
#7  0x00007ffff7989ab2 in fr_event_loop (el=0x8dbcb0) at src/lib/event.c:624
#8  0x0000000000444800 in radius_event_process () at src/main/process.c:5438
#9  0x000000000042f574 in main (argc=4, argv=0x7fffffffe698) at src/main/radiusd.c:581

(gdb) print sock
$1 = (listen_socket_t *) 0x9983d0

(gdb) print *sock
$2 = {my_ipaddr = {af = 2, ipaddr = {ip4addr = {s_addr = 0}, ip6addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}, prefix = 32 ' ', scope = 0}, my_port = 2083, interface = 0x0, 
  broadcast = 0, rate_time = 0, rate_pps_old = 0, rate_pps_now = 0, max_rate = 0, home = 0x0, other_ipaddr = {af = 2, ipaddr = {ip4addr = {s_addr = 381383107}, ip6addr = {__in6_u = {__u6_addr8 = "\303q\273\026", '\000' <repeats 11 times>, __u6_addr16 = {29123, 5819, 0, 
            0, 0, 0, 0, 0}, __u6_addr32 = {381383107, 0, 0, 0}}}}, prefix = 32 ' ', scope = 0}, other_port = 56490, proto = 6, last_packet = 1436358361, opened = 1436357665, ev = 0x0, limit = {max_connections = 16, num_connections = 1, max_requests = 0, 
    num_requests = 0, lifetime = 0, idle_timeout = 30}, parent = 0x985a90, client = 0x9947a0, packet = 0x9bcbe0, ssn = 0x999650, request = 0x998780, certs = 0x0, mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, 
      __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, data = 0x0, partial = 0, clients = 0x993fb0}

(gdb) print sock->packet
$4 = (RADIUS_PACKET *) 0x9bcbe0

(gdb) print *sock->packet
$5 = {sockfd = 19, src_ipaddr = {af = 2, ipaddr = {ip4addr = {s_addr = 381383107}, ip6addr = {__in6_u = {__u6_addr8 = "\303q\273\026", '\000' <repeats 11 times>, __u6_addr16 = {29123, 5819, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {381383107, 0, 0, 0}}}}, prefix = 32 ' ', 
    scope = 0}, dst_ipaddr = {af = 2, ipaddr = {ip4addr = {s_addr = 0}, ip6addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}, prefix = 32 ' ', scope = 0}, src_port = 56490, dst_port = 2083, 
  id = -1, code = 0, vector = '\000' <repeats 15 times>, timestamp = {tv_sec = 0, tv_usec = 0}, data = 0x0, data_len = 0, vps = 0x0, offset = -1, partial = 0, proto = 0}
(gdb)
```

If any further information needed please let me know.

**Comment by arr2036** [comment]
Debug output would be nice
