### ISSUE TITLE
segfault in 3.0.12 with -Xx and LDAP/SASL/GSSAPI

### ISSUE THREAD

**Issue by candlerb** [FreeRADIUS/freeradius-server#1824]
# Issue type

- [X] Defect - Crash or memory corruption.

# Defect/Feature description

## How to reproduce issue

Run freeradius with LDAP module and GSSAPI authentication, and environment variables pointing to keytab.

~~~
KRB5_CLIENT_KTNAME=/etc/radiusd.keytab KRB5CCNAME=MEMORY: radiusd -Xx
~~~

* `freeradius -X` is fine
* `freeradius -Xx` causes a segfault
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring

```text
...
Fri Nov  4 15:44:58 2016 : Info: rlm_ldap (ldap): Opening additional connection (0), 1 of 32 pending slots used
Fri Nov  4 15:44:58 2016 : Debug: rlm_ldap (ldap): Connecting to ldap://ipa-1.int.example.com:389
Fri Nov  4 15:44:58 2016 : Debug: rlm_ldap (ldap): New libldap handle 0x56082db5b3e0
Fri Nov  4 15:44:58 2016 : Debug: rlm_ldap (ldap): Starting SASL mech(s): GSSAPI
SASL/GSSAPI authentication started
Fri Nov  4 15:44:58 2016 : Debug: rlm_ldap (ldap): SASL challenge : Authorization Name
Fri Nov  4 15:44:58 2016 : Debug: rlm_ldap (ldap): SASL prompt    : Please enter your authorization name
Fri Nov  4 15:44:58 2016 : Debug: rlm_ldap (ldap): SASL result    :
Fri Nov  4 15:44:59 2016 : Debug: rlm_ldap (ldap): Continuing SASL mech GSSAPI...
Fri Nov  4 15:44:59 2016 : Debug: rlm_ldap (ldap): SASL response  : `???	*?H???????
Fri Nov  4 15:44:59 2016 : Debug: rlm_ldap (ldap): Continuing SASL mech GSSAPI...
Fri Nov  4 15:44:59 2016 : Debug: rlm_ldap (ldap): SASL response  : ????
Fri Nov  4 15:44:59 2016 : Debug: rlm_ldap (ldap): Continuing SASL mech (null)...
Segmentation fault (core dumped)
```

## Full backtrace from LLDB or GDB

```text
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2da0d8d in rlm_ldap_sasl_interactive (inst=inst@entry=0x555555a18320,
    request=request@entry=0x0, conn=0x555555a363c0, identity=identity@entry=0x7ffff2da3e42 "",
    password=password@entry=0x0, sasl=sasl@entry=0x555555a18358, error=error@entry=0x7fffffffe038,
    extra=extra@entry=0x7fffffffe040) at src/modules/rlm_ldap/sasl.c:175
175					escaped = fr_aprints(request, srv_cred->bv_val, srv_cred->bv_len, '\0');
(gdb) bt
#0  0x00007ffff2da0d8d in rlm_ldap_sasl_interactive (inst=inst@entry=0x555555a18320,
    request=request@entry=0x0, conn=0x555555a363c0, identity=identity@entry=0x7ffff2da3e42 "",
    password=password@entry=0x0, sasl=sasl@entry=0x555555a18358, error=error@entry=0x7fffffffe038,
    extra=extra@entry=0x7fffffffe040) at src/modules/rlm_ldap/sasl.c:175
#1  0x00007ffff2d9bc97 in rlm_ldap_bind (inst=inst@entry=0x555555a18320,
    request=request@entry=0x0, pconn=pconn@entry=0x7fffffffe0b8, dn=0x7ffff2da3e42 "",
    password=0x0, sasl=0x555555a18358, retry=retry@entry=false) at src/modules/rlm_ldap/ldap.c:717
#2  0x00007ffff2d9d870 in mod_conn_create (ctx=<optimized out>, instance=0x555555a18320)
    at src/modules/rlm_ldap/ldap.c:1527
#3  0x0000555555583105 in fr_connection_spawn (pool=pool@entry=0x555555a31bf0,
    now=now@entry=1478274255, in_use=in_use@entry=false) at src/main/connection.c:430
#4  0x0000555555583c8a in fr_connection_pool_init (ctx=0x55555599a9d0, cs=<optimized out>,
    opaque=opaque@entry=0x555555a18320, c=c@entry=0x7ffff2d9d530 <mod_conn_create>, a=a@entry=0x0,
    log_prefix=log_prefix@entry=0x7fffffffe210 "rlm_ldap (ldap)",
    trigger_prefix=trigger_prefix@entry=0x7fffffffe1d0 "modules.ldap.")
    at src/main/connection.c:1091
#5  0x000055555558412b in fr_connection_pool_module_init (module=<optimized out>,
    opaque=opaque@entry=0x555555a18320, c=0x7ffff2d9d530 <mod_conn_create>, a=a@entry=0x0,
    log_prefix=0x7fffffffe210 "rlm_ldap (ldap)", log_prefix@entry=0x0)
    at src/main/connection.c:1195
#6  0x00007ffff2d99518 in mod_instantiate (conf=0x5555559960e0, instance=0x555555a18320)
    at src/modules/rlm_ldap/rlm_ldap.c:1173
#7  0x0000555555579e24 in module_instantiate (modules=modules@entry=0x555555987d40,
    askedname=0x5555559961e0 "ldap") at src/main/modules.c:758
#8  0x000055555557aff1 in modules_init (config=0x5555557e0c50) at src/main/modules.c:2107
#9  0x000055555556810b in main (argc=2, argv=0x7fffffffe528) at src/main/radiusd.c:472
(gdb)
```

It appears to be using null pointers:

```
(gdb) print request
$1 = (REQUEST *) 0x0
(gdb) print srv_cred->bv_val
Cannot access memory at address 0x8
(gdb) print srv_cred
$2 = (struct berval *) 0x0
```

but the guard allows a null request if DEBUG_ENABLED3 is set:

```
if (((request && RDEBUG_ENABLED3) || DEBUG_ENABLED3) && result) {
```

**Comment by alandekok** [comment]
This issue should be fixed.  I'm closing this.  Please re-open if it is still a problem.

**Comment by candlerb** [comment]
Tested with freeradius git 3.0.x branch as of Dec 7 2016; the problem is indeed fixed. Thank you!
