### ISSUE TITLE
freeradius 3.0.15 crash on ldap bind, when compiled w/o sasl support

### ISSUE THREAD

**Issue by egroeper** [FreeRADIUS/freeradius-server#2110]
# Issue type
- [X] Defect - Crash or memory corruption.

# Defect/Feature description

It seems like there is a problem with LDAP auth, if freeradius was compiled without SASL support.
I'm testing with freeradius 3.0.15 (d253cf86d7).

The following patch seems to workaround the problem, but I'm not sure if this is a proper fix.
Of course I will provide this as PR as well (don't hurt me with my keyboard), if it is suitable.

```
diff --git a/src/modules/rlm_ldap/ldap.c b/src/modules/rlm_ldap/ldap.c
index d83f0a0..8ae5c34 100644
--- a/src/modules/rlm_ldap/ldap.c
+++ b/src/modules/rlm_ldap/ldap.c
@@ -698,7 +698,9 @@ ldap_rcode_t rlm_ldap_bind(rlm_ldap_t const *inst, REQUEST *request, ldap_handle
        rad_assert(!retry || inst->pool);
 
 #ifndef WITH_SASL
-       rad_assert(!sasl->mech);
+       if (sasl) {
+               rad_assert(!sasl->mech);
+       }
 #endif
 
        /*
```

It seems like in rlm_ldap.c:1313 NULL is given as sasl. And then the NULL pointer is dereferenced for the assert.

## How to reproduce issue
./configure --prefix=/usr2/freeradius
make
make install
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring

(0) ldap_cms2: Waiting for search result...
(0) ldap_cms2: User object found at DN "uid=radiuste"
Segmentation fault (core dumped)

## Full backtrace from LLDB or GDB

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr2/freeradius/sbin/radiusd -X'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa6872347af in rlm_ldap_bind (inst=0xb0d050, request=0xdf1d70, 
    pconn=0x7ffdaf0a52f8, 
    dn=0xdfd780 "uid=radiuste", 
    password=0xdf21f0 "password", sasl=0x0, retry=true)
    at src/modules/rlm_ldap/ldap.c:701
701		rad_assert(!sasl->mech);
(gdb) bt
#0  0x00007fa6872347af in rlm_ldap_bind (inst=0xb0d050, request=0xdf1d70, 
    pconn=0x7ffdaf0a52f8, 
    dn=0xdfd780 "uid=radiuste", 
    password=0xdf21f0 "password", sasl=0x0, retry=true)
    at src/modules/rlm_ldap/ldap.c:701
#1  0x00007fa687230ee5 in mod_authenticate (instance=0xb0d050, 
    request=0xdf1d70) at src/modules/rlm_ldap/rlm_ldap.c:1313
#2  0x000000000042b0f6 in call_modsingle (component=MOD_AUTHENTICATE, 
    sp=0xd96b70, request=0xdf1d70) at src/main/modcall.c:302
#3  0x000000000042b847 in modcall_recurse (request=0xdf1d70, 
    component=MOD_AUTHENTICATE, depth=2, entry=0x7ffdaf0a7420, 
    do_next_sibling=false) at src/main/modcall.c:578
#4  0x000000000042b2be in modcall_child (request=0xdf1d70, 
    component=MOD_AUTHENTICATE, depth=2, entry=0x7ffdaf0a7408, c=0xd96b70, 
    result=0x7ffdaf0a66a0, do_next_sibling=false) at src/main/modcall.c:408
#5  0x000000000042cb69 in modcall_recurse (request=0xdf1d70, 
    component=MOD_AUTHENTICATE, depth=1, entry=0x7ffdaf0a7408, 
    do_next_sibling=true) at src/main/modcall.c:964
#6  0x000000000042b2be in modcall_child (request=0xdf1d70, 
    component=MOD_AUTHENTICATE, depth=1, entry=0x7ffdaf0a73f0, c=0xd95880, 
    result=0x7ffdaf0a6d80, do_next_sibling=true) at src/main/modcall.c:408
#7  0x000000000042c336 in modcall_recurse (request=0xdf1d70, 
---Type <return> to continue, or q <return> to quit---
    component=MOD_AUTHENTICATE, depth=0, entry=0x7ffdaf0a73f0, 
    do_next_sibling=true) at src/main/modcall.c:789
#8  0x000000000042d1a8 in modcall (component=MOD_AUTHENTICATE, c=0xd95780, 
    request=0xdf1d70) at src/main/modcall.c:1134
#9  0x000000000042860a in indexed_modcall (comp=MOD_AUTHENTICATE, 
    idx=13246194, request=0xdf1d70) at src/main/modules.c:1028
#10 0x000000000042a9e6 in process_authenticate (auth_type=13246194, 
    request=0xdf1d70) at src/main/modules.c:2169
#11 0x000000000040f82c in rad_check_password (request=0xdf1d70)
    at src/main/auth.c:252
#12 0x0000000000410301 in rad_authenticate (request=0xdf1d70)
    at src/main/auth.c:583
#13 0x0000000000440897 in request_running (request=0xdf1d70, action=1)
    at src/main/process.c:1536
#14 0x000000000043f58a in request_queue_or_run (request=0xdf1d70, 
    process=0x440735 <request_running>) at src/main/process.c:1024
#15 0x0000000000441129 in request_receive (ctx=0xdf1b70, listener=0xdb5b40, 
    packet=0xdf1bd0, client=0xdb6290, fun=0x40fd63 <rad_authenticate>)
    at src/main/process.c:1792
#16 0x0000000000419543 in auth_socket_recv (listener=0xdb5b40)
    at src/main/listen.c:1571
#17 0x0000000000448829 in event_socket_handler (xel=0xa1a8b0, fd=18, 
    ctx=0xdb5b40) at src/main/process.c:4593
---Type <return> to continue, or q <return> to quit---
#18 0x00007fa6897848da in fr_event_loop (el=0xa1a8b0) at src/lib/event.c:649
#19 0x000000000044a7ee in radius_event_process () at src/main/process.c:5668
#20 0x0000000000433d19 in main (argc=2, argv=0x7ffdaf0a8328)
    at src/main/radiusd.c:585
(gdb) 
```

**Comment by arr2036** [comment]
If the server isn't compiled with SASL support there should be no sasl mech... That's the real issue here.
