### ISSUE TITLE
Issue with backported atomic queues

### ISSUE THREAD

**Issue by pauldekkers** [FreeRADIUS/freeradius-server#2298]
# Issue type

- Defect - Crash or memory corruption.

Running production workload on a recently updated 3.0.x source tree, I noticed a couple of crashes (thanks to systemd for restarting ;-)) that may have to do with the backported atomic queues from v4 in cda187ef99a4ebd64e435e7b59c2e4645e4fb965

My other server that receives about the same amount of traffic that only got the source as far as 1f2824735e8d5723e59494cd8f02bb9329b2d0f6 doens't have the crashes and runs for days.

As this is a recent change, I hope it's helpful to report.

# Defect
## How to reproduce the issue

Running on Ubuntu 18.04.1 LTS with 3.0.x up to 6c9b1c75ccf694fd2a750d6a24df5a12f284c46d

Unfortunately, I have very little evidence (yet). This is a production server that proxies about 6Mbit/s of requests at the time (it was still quiet ;-)) and I have no idea what triggered it. What I do have from my regular logging is this:

```
ASSERT FAILED src/main/threads.c[668]: *prequest != NULL
```

for each of the crashes. As this is the area that cda187ef99a4ebd64e435e7b59c2e4645e4fb965 touched, I thought it would be useful to report - even without further debugging or logging otherwise.

I don't see events happening just before the crash that relate the crashes.

I must add that while the server crashed 6 times in half an hour, it didn't crash for the last half hour. I'll continue to monitor it, but maybe revert to something I know worked well.

Having no clue what triggered the crash, I think it might be hard to reproduce or debug further. But maybe you have an idea based on what I describe.

**Comment by pauldekkers** [comment]
Ok, I ran the server in debug (-fxxl), that wasn't too bad. I have four crashes logged. It looks like I have at least two crashes in a row each time.

I'm now running with 1932a4d4cdf3e7777fc525e2eb0a15cd13d1be94 and that didn't crash since. So the changes after must be relevant.

I'm copying in a `grep -v "^(" | tail -n 20` from each of them here. It might not be enough, let me know if you think other context matters. (I'm studying one loop that occurred in all samples, but I'm not sure it's relevant. It doesn't crash with 1932a4d4cdf3e7777fc525e2eb0a15cd13d1be94.)

This was the most recent crash, crashing within 10 seconds after the process before:

```
Thread 9 got semaphore
Thread 9 handling request 4710, (598 handled so far)
Thread 9 waiting to be assigned a request
Thread 1 got semaphore
Thread 1 handling request 4709, (882 handled so far)
Thread 1 waiting to be assigned a request
Thread 3 waiting to be assigned a request
Threads: total/active/spare threads = 11/0/11
Threads: deleting 1 spare out of 1 spares
Thread 8 got semaphore
ASSERT FAILED src/main/threads.c[668]: *prequest != NULL
CAUGHT SIGNAL: Aborted
Backtrace of last 6 frames:
/opt/freeradius/lib/libfreeradius-radius.so(fr_fault+0x12c)[0x7fdc187ec4b1]
/opt/freeradius/lib/libfreeradius-server.so(rad_assert_fail+0x46)[0x7fdc18a514dd]
/opt/freeradius/sbin/radiusd(+0x41466)[0x5650b923b466]
/opt/freeradius/sbin/radiusd(+0x4173f)[0x5650b923b73f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7fdc17acd6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fdc175be88f]
No panic action set
```

... so 10 seconds after this one, that ran for at least 10 minutes:

```
Thread 4 handling request 61638, (14466 handled so far)
Thread 4 waiting to be assigned a request
Threads: total/active/spare threads = 11/0/11
Threads: deleting 1 spare out of 1 spares
Thread 7 got semaphore
Thread 9 got semaphore
Thread 7 handling request 61650, (14325 handled so far)
Thread 9 handling request 61651, (601 handled so far)
Thread 9 waiting to be assigned a request
Thread 9 got semaphore
ASSERT FAILED src/main/threads.c[668]: *prequest != NULL
CAUGHT SIGNAL: Aborted
Backtrace of last 6 frames:
/opt/freeradius/lib/libfreeradius-radius.so(fr_fault+0x12c)[0x7fde904714b1]
/opt/freeradius/lib/libfreeradius-server.so(rad_assert_fail+0x46)[0x7fde906d64dd]
/opt/freeradius/sbin/radiusd(+0x41466)[0x55afbedc8466]
/opt/freeradius/sbin/radiusd(+0x4173f)[0x55afbedc873f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7fde8f7526db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fde8f24388f]
No panic action set
```

Earlier I had this crash, also within 10 seconds after the process before it ran 10 minutes:

```
Threads: deleting 1 spare out of 3 spares
Thread 9 got semaphore
Thread 9 handling request 5976, (478 handled so far)
Thread 4 got semaphore
Thread 4 handling request 5971, (1051 handled so far)
Thread 9 waiting to be assigned a request
Thread 9 got semaphore
Thread 9 handling request 5979, (479 handled so far)
Thread 4 waiting to be assigned a request
Thread 4 got semaphore
ASSERT FAILED src/main/threads.c[668]: *prequest != NULL
CAUGHT SIGNAL: Aborted
Backtrace of last 6 frames:
/opt/freeradius/lib/libfreeradius-radius.so(fr_fault+0x12c)[0x7f5ba568c4b1]
/opt/freeradius/lib/libfreeradius-server.so(rad_assert_fail+0x46)[0x7f5ba58f14dd]
/opt/freeradius/sbin/radiusd(+0x41466)[0x556dc4323466]
/opt/freeradius/sbin/radiusd(+0x4173f)[0x556dc432373f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f5ba496d6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f5ba445e88f]
No panic action set
```

... which is this one, of which I had to get 130 lines actually to capture both the assert and the server quitting:

```
Thread 16 handling request 50576, (315 handled so far)
Thread 16 waiting to be assigned a request
Thread 16 got semaphore
Thread 16 handling request 50577, (316 handled so far)
Thread 7 got semaphore
Thread 7 handling request 50574, (11392 handled so far)
Thread 16 waiting to be assigned a request
Thread 7 waiting to be assigned a request
Thread 8 got semaphore
Thread 8 handling request 50578, (11456 handled so far)
Thread 8 waiting to be assigned a request
Thread 13 got semaphore
Thread 13 handling request 50570, (339 handled so far)
Thread 13 waiting to be assigned a request
Thread 10 got semaphore
Thread 10 handling request 50579, (354 handled so far)
Thread 10 waiting to be assigned a request
Thread 12 got semaphore
Thread 12 handling request 50579, (331 handled so far)
Thread 12 waiting to be assigned a request
Thread 17 got semaphore
Thread 17 handling request 50578, (331 handled so far)
Thread 17 waiting to be assigned a request
Thread 3 got semaphore
Thread 3 handling request 50577, (11710 handled so far)
Threads: total/active/spare threads = 17/1/16
Threads: deleting 1 spare out of 6 spares
Thread 15 got semaphore
ASSERT FAILED src/main/threads.c[668]: *prequest != NULL
CAUGHT SIGNAL: Aborted
Thread 3 waiting to be assigned a request
Thread 9 got semaphore
Thread 9 handling request 50580, (340 handled so far)
Thread 9 waiting to be assigned a request
Thread 2 got semaphore
Thread 2 handling request 50573, (11686 handled so far)
Thread 2 waiting to be assigned a request
Thread 5 got semaphore
Thread 4 got semaphore
Thread 4 handling request 50581, (11645 handled so far)
Thread 5 handling request 50575, (11704 handled so far)
Thread 5 waiting to be assigned a request
Thread 4 waiting to be assigned a request
Thread 11 got semaphore
Thread 11 handling request 50582, (329 handled so far)
Thread 11 waiting to be assigned a request
Thread 6 got semaphore
Thread 6 handling request 50580, (11359 handled so far)
Thread 6 waiting to be assigned a request
Thread 14 got semaphore
Thread 14 handling request 50583, (315 handled so far)
Thread 14 waiting to be assigned a request
Thread 7 got semaphore
Thread 7 handling request 48170, (11393 handled so far)
Thread 7 waiting to be assigned a request
Thread 7 got semaphore
Thread 1 got semaphore
Thread 7 handling request 50584, (11394 handled so far)
Thread 1 handling request 50585, (11654 handled so far)
Thread 1 exiting...
Deleting thread 1
Threads: total/active/spare threads = 16/1/15
Thread 7 waiting to be assigned a request
Thread 7 got semaphore
Thread 7 handling request 50582, (11395 handled so far)
Thread 12 got semaphore
Thread 12 handling request 50576, (332 handled so far)
Thread 3 got semaphore
Thread 3 handling request 50586, (11711 handled so far)
Thread 9 got semaphore
Thread 9 handling request 50587, (341 handled so far)
Thread 2 got semaphore
Thread 2 handling request 50588, (11687 handled so far)
Thread 17 got semaphore
Thread 17 handling request 50589, (332 handled so far)
Thread 10 got semaphore
Thread 10 handling request 50590, (355 handled so far)
Thread 13 got semaphore
Thread 13 handling request 50591, (340 handled so far)
Thread 12 waiting to be assigned a request
Thread 9 waiting to be assigned a request
Thread 3 waiting to be assigned a request
Thread 7 waiting to be assigned a request
Thread 10 waiting to be assigned a request
Thread 2 waiting to be assigned a request
Thread 17 waiting to be assigned a request
Thread 5 got semaphore
Thread 5 handling request 50547, (11705 handled so far)
Thread 5 waiting to be assigned a request
Thread 13 waiting to be assigned a request
Thread 13 got semaphore
Thread 13 handling request 50592, (341 handled so far)
Thread 11 got semaphore
Thread 11 handling request 50584, (330 handled so far)
Thread 11 waiting to be assigned a request
Thread 13 waiting to be assigned a request
Thread 16 got semaphore
Thread 16 handling request 50587, (317 handled so far)
Thread 14 got semaphore
Thread 14 handling request 50586, (316 handled so far)
Thread 6 got semaphore
Thread 6 handling request 50593, (11360 handled so far)
Thread 16 waiting to be assigned a request
Thread 8 got semaphore
Thread 8 handling request 50594, (11457 handled so far)
Thread 14 waiting to be assigned a request
Thread 6 waiting to be assigned a request
Thread 8 waiting to be assigned a request
Thread 12 got semaphore
Thread 12 handling request 50581, (333 handled so far)
Thread 12 waiting to be assigned a request
Thread 9 got semaphore
Thread 9 handling request 50595, (342 handled so far)
Thread 9 waiting to be assigned a request
Thread 3 got semaphore
Thread 3 handling request 50589, (11712 handled so far)
Thread 3 waiting to be assigned a request
Thread 7 got semaphore
Thread 7 handling request 50596, (11396 handled so far)
Thread 7 waiting to be assigned a request
Backtrace of last 6 frames:
Thread 10 got semaphore
/opt/freeradius/lib/libfreeradius-radius.so(fr_fault+0x12c)[0x7f6aa58594b1]
/opt/freeradius/lib/libfreeradius-server.so(rad_assert_fail+0x46)[0x7f6aa5abe4dd]
/opt/freeradius/sbin/radiusd(+0x41466)[0x55fdcfae5466]
/opt/freeradius/sbin/radiusd(+0x4173f)[0x55fdcfae573f]
Thread 10 handling request 50590, (356 handled so far)
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f6aa4b3a6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f6aa462b88f]
No panic action set
```

**Comment by pauldekkers** [comment]
Ok, so it is actually easy to reproduce. Just create a loop! (So the loop I spotted was actually the trigger and in that regard relevant.)

```
# /opt/CURRENT/sbin/radiusd -fl stdout
Wed Sep  5 11:48:47 2018 : Info: Starting - reading configuration files ...
Wed Sep  5 11:48:47 2018 : Info: Core dumps are enabled
Wed Sep  5 11:48:47 2018 : Info: Debugger not attached
Wed Sep  5 11:48:47 2018 : Warning: [/opt/CURRENT/etc/raddb/mods-config/attr_filter/access_reject]:11 Check item "FreeRADIUS-Response-Delay"    found in filter list for realm "DEFAULT".
Wed Sep  5 11:48:47 2018 : Warning: [/opt/CURRENT/etc/raddb/mods-config/attr_filter/access_reject]:11 Check item "FreeRADIUS-Response-Delay-USec"   found in filter list for realm "DEFAULT".
Wed Sep  5 11:48:47 2018 : Info: Loaded virtual server <default>
Wed Sep  5 11:48:47 2018 : Warning: Ignoring "sql" (see raddb/mods-available/README.rst)
Wed Sep  5 11:48:47 2018 : Warning: Ignoring "ldap" (see raddb/mods-available/README.rst)
Wed Sep  5 11:48:47 2018 : Info: Loaded virtual server default
Wed Sep  5 11:48:48 2018 : Info: Ready to process requests
Wed Sep  5 11:48:57 2018 : Info: Dropping packet without response because of error: Received packet from 127.0.0.1 with invalid Message-Authenticator!  (Shared secret is incorrect.)
Wed Sep  5 11:48:58 2018 : Info:  ... adding new socket proxy address * port 57952
Wed Sep  5 11:48:58 2018 : Info:  ... adding new socket proxy address * port 57952
Wed Sep  5 11:49:00 2018 : Error: ASSERT FAILED src/main/threads.c[668]: *prequest != NULL
CAUGHT SIGNAL: Aborted
Backtrace of last 6 frames:
/opt/CURRENT/lib/libfreeradius-radius.so(fr_fault+0x12c)[0x7faaf976d4b1]
/opt/CURRENT/lib/libfreeradius-server.so(rad_assert_fail+0x46)[0x7faaf99d24dd]
/opt/CURRENT/sbin/radiusd(+0x41522)[0x56475edf4522]
/opt/CURRENT/sbin/radiusd(+0x417fb)[0x56475edf47fb]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7faaf8a4e6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7faaf853f88f]
No panic action set
Aborted (core dumped)
```

Crash within 3 seconds. And I did send a lot of requests to the server meanwhile, that also looped to itself.

And the backtrace:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/CURRENT/sbin/radiusd -fl stdout'.
Program terminated with signal SIGABRT, Aborted.
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
51  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7faad7fff700 (LWP 31934))]
(gdb) bt
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007faaf976d77e in fr_fault (sig=6) at src/lib/debug.c:755
#2  0x00007faaf99d24dd in rad_assert_fail (file=0x56475ee2812a "src/main/threads.c", line=668, expr=0x56475ee28199 "*prequest != NULL") at src/main/util.c:557
#3  0x000056475edf4522 in request_dequeue (prequest=0x56475f979810) at src/main/threads.c:668
#4  0x000056475edf47fb in request_handler_thread (arg=0x56475f9797e0) at src/main/threads.c:781
#5  0x00007faaf8a4e6db in start_thread (arg=0x7faad7fff700) at pthread_create.c:463
#6  0x00007faaf853f88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Still, the crashes only happen with the atomic patches applied. Running with 1932a4d4cdf3e7777fc525e2eb0a15cd13d1be94 and all is fine.

**Comment by pauldekkers** [comment]
That does seem to fix it. Thanks.

(I'm not closing this issue because I don't know if you want to leave it open to fix the code for eg. v4 if that's also necessary. But as far as I'm concerned it can be closed. This was also the reason I didn't close #2284 but maybe I should go ahead and do that as well.)
