### ISSUE TITLE
freeradius: segfault in rlm_preprocess-2.2.1.so

### ISSUE THREAD

**Issue by netflash** [FreeRADIUS/freeradius-server#345]
commit c58e147e327f6333c4a96b0f495650f650327122

I have again almost the same issue, as issue #141 

gdb output

```
Wed Jul  3 14:42:21 2013 : Debug: Listening on proxy address * port 18122
Wed Jul  3 14:42:21 2013 : Info: Ready to process requests.


rad_recv: Access-Request packet from host 10.90.240.51 port 1884, id=38, length=176
    Framed-MTU = 1480
    NAS-IP-Address = 10.90.240.51
    NAS-Identifier = "Test_1"
    User-Name = "20cf308cbcea"
    Service-Type = Call-Check
    Framed-Protocol = PPP
    NAS-Port = 2
    NAS-Port-Type = Ethernet
    NAS-Port-Id = "2"
    Called-Station-Id = "00-1d-b3-bc-8d-be"
    Calling-Station-Id = "20-cf-30-8c-bc-ea"
    Connect-Info = "CONNECT Ethernet 100Mbps Full duplex"
    CHAP-Password = 0x257c7c72e41921593a9f6950c5fc7af174
Wed Jul  3 14:44:40 2013 : Info: # Executing section authorize from file /usr/local/freeradius/etc/raddb/sites-enabled/default
Wed Jul  3 14:44:40 2013 : Info: +- entering group authorize {...}

Program received signal SIGSEGV, Segmentation fault.
rad_mangle (data=0xdf2a60, request=0xe02930) at rlm_preprocess.c:219
219     request_pairs = request->packet->vps;
(gdb) 
(gdb) 
(gdb) print request->packet
$1 = (RADIUS_PACKET *) 0xdeadbeef
(gdb) print request->packet->vps
Cannot access memory at address 0xdeadbf5f
(gdb) bt
#0  rad_mangle (data=0xdf2a60, request=0xe02930) at rlm_preprocess.c:219
#1  0x00007ffff2067908 in preprocess_authorize (instance=0xdf2a60, request=0x1) at rlm_preprocess.c:542
#2  0x000000000041dc5d in call_modsingle (component=<value optimized out>, c=<value optimized out>, request=0xe02930) at modcall.c:304
#3  modcall (component=<value optimized out>, c=<value optimized out>, request=0xe02930) at modcall.c:684
#4  0x000000000041a173 in indexed_modcall (comp=1, idx=0, request=0xe02930) at modules.c:750
#5  0x0000000000409858 in rad_authenticate (request=0xe02930) at auth.c:580
#6  0x000000000042ae2e in radius_handle_request (request=0xe02930, fun=0x409600 <rad_authenticate>) at event.c:3814
#7  0x000000000042179d in thread_pool_addrequest (request=0xdf2a60, fun=0x409600 <rad_authenticate>) at threads.c:921
#8  0x000000000042c47e in event_socket_handler (xel=<value optimized out>, fd=<value optimized out>, ctx=<value optimized out>) at event.c:3456
#9  0x00007ffff786193b in fr_event_loop (el=0xdfb720) at event.c:415
#10 0x000000000041e70a in main (argc=4, argv=<value optimized out>) at radiusd.c:421
```

**Comment by madf** [comment]
Today I've faced the same error with my own FreeRADIUS module and I've spent almost the whole day to figure out the problem. Now it is clear: RADIUS_PACKET structure depends on NDEBUG flag. When it is not defined (debug-mode) the structure has one additional field - magic, which equals to 0xdeadbeef. If the module is linked with NDEBUG and the server is linked without it, magic is substituted with packet, so it has a wrong value 0xdeadbeef.

**Comment by arr2036** [comment]
In v3.0.x we have better version compatibility checking that prevents modules from different versions of the server from being loaded. It also prevents use of developer build modules with non developer versions of the server and vice versa.
