### ISSUE TITLE
SIGSEGV when calling external CoA disconnect script

### ISSUE THREAD

**Issue by frankerooney** [FreeRADIUS/freeradius-server#3545]
# Issue type
- Defect - Crash or memory corruption.

# Defect
Crash occurs when calling CoA disconnect script (working in v3.1).

CoA script is in bash, called via:

      CoA-Disconnect {
        fail=1
        reject=1
      }

exec mods-enabled contains:
exec CoA-Disconnect {
        wait = yes
        input_pairs=config
        output_pairs=config
        shell_escape = yes
        program = "${raddbdir}/executables/coa_disconnect.sh --username %{control:CoA-User-Name} --acctsessionid %{control:CoA-Acct-Session-ID} --nasipaddress %{NAS-IP-Address}"
}

The
if (&control:Cached-Ldap-CoA-Group && &control:Cached-Ldap-CoA-Group[*] == "MBA_NoTimeout") {
at the start of the debug output is just a check to see if that particular mac address "user" is part of an AD group preventing CoA logoff, some devices never send any traffic once logged off, and so don't spawn a new access request, most fall into the ..else branch as seen here.

(hopefully useful) background, optional read explaining what we're doing : The specific "CoA-User-Name" is derived from the mac address of what a sql query says is connected to the switch port the current user name is connected to, stored in an external database. Sometimes this "CoA username" isn't the presenting user name, hence the alternative attribute. 
Usually the CoA action is used to log off stale accepted mac entries from a switch when an updated mac is presented, e.g. IP phones have an internal switch which allow a sub-device plugged into them; the main upstream switch doesn't get notified when the sub-device is removed from the phone and a new one connected, and we only allow a preset number of macs on the switch ports, needing this CoA action to remove stale entries.

A clear and concise list of steps describing how to describe the issue.

Have a device plug into an upstream switch with the condition that requires a CoA.
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring

(0)                if (&control:Cached-Ldap-CoA-Group && &control:Cached-Ldap-CoA-Group[*] == "MBA_NoTimeout") {
(0)                  ...
(0)                }
(0)                else {
(0)                  CoA-Disconnect (yield)
(0)                  EXPAND /etc/freeradius/executables/coa_disconnect.sh
(0)                    --> /etc/freeradius/executables/coa_disconnect.sh
(0)                  EXPAND --username
(0)                    --> --username
(0)                  EXPAND %{control:CoA-User-Name}
(0)                    --> b827ebb46346
(0)                  EXPAND %{control:CoA-User-Name}
(0)                    --> b827ebb46346
(0)                  EXPAND --acctsessionid
(0)                    --> --acctsessionid
(0)                  EXPAND %{control:CoA-Acct-Session-ID}
(0)                    --> 001C00000358
(0)                  EXPAND %{control:CoA-Acct-Session-ID}
(0)                    --> 001C00000358
(0)                  EXPAND --nasipaddress
(0)                    --> --nasipaddress
(0)                  EXPAND %{NAS-IP-Address}
(0)                    --> 192.168.105.142
(0)                  EXPAND %{NAS-IP-Address}
(0)                    --> 192.168.105.142
[Detaching after fork from child process 1519551]
(0) -: Expected Disconnect-ACK got Disconnect-NAK
_EXIT(1) CALLED src/bin/radclient.c[1630]
(0)                  Running request
(0)                  tmpl - Resuming execution
(0)                  Program failed with status code 1
(0)                  CoA-Disconnect - EXEC GOT -- (null)

Program received signal SIGSEGV, Segmentation fault.
fr_pair_list_afrom_box (ctx=0x5555574b4710, dict=0x5555555bbf90, box=0x0) at src/lib/util/pair.c:2692
2692    src/lib/util/pair.c: No such file or directory.
(gdb) bt
#0  fr_pair_list_afrom_box (ctx=0x5555574b4710, dict=0x5555555bbf90, box=0x0) at src/lib/util/pair.c:2692
#1  0x00007ffff6cc5790 in mod_exec_wait_resume (mctx=<optimized out>, request=0x5555574b4710, rctx=<optimized out>)
    at src/modules/rlm_exec/rlm_exec.c:309
#2  0x00007ffff7e93df3 in unlang_module_resume (request=0x5555574b4710, presult=0x5555574b48e0) at src/lib/unlang/module.c:653
#3  0x00007ffff7e90069 in frame_eval (priority=0x7fffffffe214, result=0x5555574b48e0, frame=0x5555574b4b20, request=0x5555574b4710)
    at src/lib/unlang/interpret.c:475
#4  unlang_interpret (request=request@entry=0x5555574b4710) at src/lib/unlang/interpret.c:645
#5  0x00007ffff6e10c68 in mod_process (mctx=<optimized out>, request=0x5555574b4710)
    at src/modules/proto_radius/proto_radius_auth.c:313
#6  0x00007ffff7e68e45 in worker_run_request (worker=0x55555737a110, start=176712355994) at src/lib/io/worker.c:900
#7  0x00007ffff7df5dd3 in fr_event_service (el=0x55555737dde0) at src/lib/util/event.c:2060
#8  fr_event_service (el=0x55555737dde0) at src/lib/util/event.c:1811
#9  0x00007ffff7df6258 in fr_event_loop (el=0x55555737dde0) at src/lib/util/event.c:2100
#10 0x00007ffff7f10adf in main_loop_start () at src/lib/server/main_loop.c:214
#11 0x000055555555a1f9 in main (argc=<optimized out>, argv=<optimized out>) at src/bin/radiusd.c:924

Thanks! Andy

**Comment by frankerooney** [comment]
Thanks Alan :-)
