### ISSUE TITLE
[defect]: typo in configuration causes runtime SEGV

### ISSUE THREAD

**Issue by jimdigriz** [FreeRADIUS/freeradius-server#5322]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

Looks like the parser trips up on this:
```
%{substring %{outer.request:Tmp-String-0} 2 18}
```

Notice the missing `:` after `substring`.

This happens at runtime rather than start.

### Log output from the FreeRADIUS daemon

```shell
N/A
```

### Backtrace from LLDB or GDB

```shell
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff72edaac in substring_xlat (instance=<optimized out>, request=0x555555a776b0, fmt=0x0, out=0x555555c44350 "f0248b684157f289ab", outlen=2048) at src/modules/rlm_unpack/rlm_unpack.c:290
warning: Source file is more recent than executable.
290		while (isspace((uint8_t) *p) && p++);
(gdb) where
#0  0x00007ffff72edaac in substring_xlat (instance=<optimized out>, request=0x555555a776b0, fmt=0x0, out=0x555555c44350 "f0248b684157f289ab", outlen=2048) at src/modules/rlm_unpack/rlm_unpack.c:290
#1  0x00007ffff7fa41cd in xlat_aprint (ctx=0x555555c4e600, request=0x555555a776b0, node=0x555555bfdb80, escape=0x0, escape_ctx=0x0, lvl=0) at src/main/xlat.c:2301
#2  0x00007ffff7fa498c in xlat_process (out=0x7fffffffbe70, request=0x555555a776b0, head=<optimized out>, escape=0x0, escape_ctx=0x0) at src/main/xlat.c:2500
#3  0x00007ffff7fa5dfe in xlat_expand_struct (escape_ctx=<optimized out>, escape=<optimized out>, node=<optimized out>, request=<optimized out>, outlen=0, out=0x7fffffffbf00) at src/main/xlat.c:2554
#4  radius_axlat_struct (out=0x7fffffffbf00, request=<optimized out>, xlat=<optimized out>, escape=<optimized out>, ctx=<optimized out>) at src/main/xlat.c:2695
#5  0x00007ffff7f9a145 in map_to_vp (ctx=0x555555c361e0, out=0x7fffffffc3d0, request=0x555555a776b0, map=0x555555bd46b0, uctx=<optimized out>) at src/main/map.c:824
#6  0x00007ffff7f9a729 in map_to_request (request=request@entry=0x555555a776b0, map=map@entry=0x555555bd46b0, func=func@entry=0x7ffff7f99f40 <map_to_vp>, ctx=ctx@entry=0x0) at src/main/map.c:1152
#7  0x0000555555580c7d in modcall_recurse (request=0x555555a776b0, component=MOD_AUTHORIZE, depth=1, entry=0x7fffffffc978, do_next_sibling=true) at src/main/modcall.c:602
#8  0x00005555555815b3 in modcall_child (request=request@entry=0x555555a776b0, component=component@entry=MOD_AUTHORIZE, depth=depth@entry=1, entry=entry@entry=0x7fffffffc960, c=<optimized out>, 
    result=result@entry=0x7fffffffc7c4, do_next_sibling=true) at src/main/modcall.c:410
#9  0x00005555555803fb in modcall_recurse (request=0x555555a776b0, component=MOD_AUTHORIZE, depth=0, entry=0x7fffffffc960, do_next_sibling=true) at src/main/modcall.c:795
#10 0x000055555557fdd5 in modcall (component=component@entry=MOD_AUTHORIZE, c=c@entry=0x555555bcaf60, request=request@entry=0x555555a776b0) at src/main/modcall.c:1140
#11 0x000055555557ff5e in indexed_modcall (comp=MOD_AUTHORIZE, idx=<optimized out>, request=0x555555a776b0) at src/main/modules.c:1025
#12 0x000055555557007a in process_authorize (request=0x555555a776b0, autz_type=0) at src/main/modules.c:2209
#13 rad_authenticate (request=request@entry=0x555555a776b0) at src/main/auth.c:519
#14 0x0000555555570b75 in rad_virtual_server (request=request@entry=0x555555a776b0) at src/main/auth.c:839
#15 0x00007ffff67c6f60 in eapttls_process (handler=handler@entry=0x555555c34030, tls_session=tls_session@entry=0x7ffff66e6070) at src/modules/rlm_eap/types/rlm_eap_ttls/ttls.c:1217
#16 0x00007ffff67c793d in mod_process (arg=0x555555b95d40, handler=0x555555c34030) at src/modules/rlm_eap/types/rlm_eap_ttls/rlm_eap_ttls.c:333
#17 0x00007ffff718cde8 in eap_module_call (module=0x555555b97ba0, handler=handler@entry=0x555555c34030) at src/modules/rlm_eap/eap.c:194
#18 0x00007ffff718d6f1 in eap_method_select (inst=inst@entry=0x5555558ac2e0, handler=handler@entry=0x555555c34030) at src/modules/rlm_eap/eap.c:464
#19 0x00007ffff718ffe8 in mod_authenticate (instance=0x5555558ac2e0, request=0x555555c42570) at src/modules/rlm_eap/rlm_eap.c:333
#20 0x0000555555580576 in call_modsingle (request=0x555555c42570, sp=<optimized out>, component=MOD_AUTHENTICATE) at src/main/modcall.c:304
#21 modcall_recurse (request=0x555555c42570, component=MOD_AUTHENTICATE, depth=1, entry=0x7fffffffd9a8, do_next_sibling=true) at src/main/modcall.c:584
#22 0x00005555555815b3 in modcall_child (request=request@entry=0x555555c42570, component=component@entry=MOD_AUTHENTICATE, depth=depth@entry=1, entry=entry@entry=0x7fffffffd990, c=<optimized out>, 
    result=result@entry=0x7fffffffd7f4, do_next_sibling=true) at src/main/modcall.c:410
#23 0x00005555555803fb in modcall_recurse (request=0x555555c42570, component=MOD_AUTHENTICATE, depth=0, entry=0x7fffffffd990, do_next_sibling=true) at src/main/modcall.c:795
#24 0x000055555557fdd5 in modcall (component=component@entry=MOD_AUTHENTICATE, c=c@entry=0x555555beb380, request=request@entry=0x555555c42570) at src/main/modcall.c:1140
#25 0x000055555557ff5e in indexed_modcall (comp=MOD_AUTHENTICATE, idx=<optimized out>, request=0x555555c42570) at src/main/modules.c:1025
#26 0x0000555555570284 in process_authenticate (request=0x555555c42570, auth_type=9872737) at src/main/modules.c:2217
#27 rad_check_password (request=0x555555c42570) at src/main/auth.c:258
#28 rad_authenticate (request=0x555555c42570) at src/main/auth.c:607
#29 0x0000555555592de0 in request_running (request=0x555555c42570, action=<optimized out>) at src/main/process.c:1693
#30 0x00005555555902a1 in request_queue_or_run (request=request@entry=0x555555c42570, process=process@entry=0x555555592ce0 <request_running>) at src/main/process.c:1156
#31 0x0000555555591625 in request_receive (ctx=<optimized out>, listener=0x555555b955f0, packet=<optimized out>, client=0x555555881fd0, fun=0x55555556ffb0 <rad_authenticate>) at src/main/process.c:2006
#32 0x00005555555779ed in auth_socket_recv (listener=0x555555b955f0) at src/main/listen.c:2064
#33 0x00007ffff7f6bfa4 in fr_event_loop (el=0x555555884850) at src/lib/event.c:713
#34 0x000055555556c534 in main (argc=<optimized out>, argv=<optimized out>) at src/main/radiusd.c:634
```

**Comment by alandekok** [comment]
fixed in commit bda81b8d6e
