### ISSUE TITLE
FreeRADIUS 3.0.6 build process not deploying DHCP protocol modules on Ubuntu

### ISSUE THREAD

**Issue by mixja** [FreeRADIUS/freeradius-server#869]
Hi

I am using Ubuntu 14.04.1 with the FreeRADIUS 3.0.6 release branch and have modified the debian/rules file as follows to include DHCP, disabled openssl version check and added some experimental modules:

```
	./configure $(confflags) \
		--config-cache \
		--with-dhcp \
		--disable-developer \
		--disable-openssl-version-check \
		--prefix=/usr \
		--exec-prefix=/usr \
		--mandir=$(mandir) \
		--sysconfdir=/etc \
		--libdir=$(libdir) \
		--datadir=/usr/share \
		--localstatedir=/var \
		--with-raddbdir=$(raddbdir) \
		--with-logdir=/var/log/$(package) \
		--with-large-files \
		--with-udpfromto \
		--without-rlm_eap_tnc \
		--with-rlm_sql_postgresql_lib_dir=`pg_config --libdir` \
		--with-rlm_sql_postgresql_include_dir=`pg_config --includedir` \
		--without-rlm_eap_ikev2 \
		--without-rlm_sql_oracle \
		--without-rlm_sql_unixodbc \
		--with-experimental-modules \
		--with-jsonc-include-dir=/usr/include/json-c \
		--with-jsonc-lib-dir=/usr/lib/x86_64-linux-gnu \
		--with-redis-include-dir=/usr/include/hiredis \
		--with-redis-lib-dir=/usr/lib/x86_64-linux-gnu
```

I build and install Debian packages as follows in the FreeRADIUS repository root:
```
sudo fakeroot dpkg-buildpackage -b -uc
sudo dpkg -i ../*freeradius*_3.0.6*_*.deb
```
This completes successfully and the FreeRADIUS service starts OK.

If I now add a DHCP configuration to sites-enabled however, FreeRADIUS crashes with a segmentation fault:
```
Tue Jan  6 15:47:59 2015 : Debug: radiusd: #### Opening IP addresses and Ports ####
Tue Jan  6 15:47:59 2015 : Debug: Loading library using absolute path "proto_dhcp"
Tue Jan  6 15:47:59 2015 : Debug: Library file not found
Tue Jan  6 15:47:59 2015 : Debug: Falling back to linker search path(s)
Tue Jan  6 15:47:59 2015 : Debug: listen {
Tue Jan  6 15:47:59 2015 : Debug:   	type = "dhcp"
Segmentation fault
```
The problem seems to be that proto_dhcp module files were not installed during deployment phase.  They are being built and if I manually copy them to /usr/lib/freeradius then the DHCP configuration loads and FreeRADIUS starts OK:
```
cp /usr/local/src/freeradius/freeradius-server/debian/tmp/usr/lib/freeradius/proto_dhcp* .
chmod 644 /usr/lib/freeradius/proto_dhcp.*
```

**Comment by arr2036** [comment]
Debian packages probably need updating, they're likely not installed by default... This is how debian packaging works, you need to explicitly state what gets included. You're welcome to create a freeradius-dhcp package.

Regarding the segfault, could you post the backtrace so we can fix it...

**Comment by herwinw** [comment]
Got it reproduced at a debian system with release_3_0_6. The backtrace:

```
#0  0x00000000 in ?? ()
#1  0x080605c2 in listen_parse (cs=0x82562f0, server=0x82561a8 "dhcp") at src/main/listen.c:2893
#2  0x08060c9a in listen_init (config=0x81e9a60, head=0xffffd90c, spawn_flag=false) at src/main/listen.c:3146
#3  0x0807f0e4 in radius_event_start (cs=0x81e9a60, have_children=false) at src/main/process.c:5023
#4  0x0806cc36 in main (argc=2, argv=0xffffda34) at src/main/radiusd.c:471
```

Reformatted print of master_listen:
```
{
  {magic = 17582897398871087440, name = 0x8090570 "status", inst_size = 192, proto_config = 0x0, parse = 0x8058404 <common_socket_parse>, free = 0x0, recv = 0x8058f7f <stats_socket_recv>, send = 0x8058c9f <auth_socket_send>, print = 0x805792a <common_socket_print>, encode = 0x805a46e <client_socket_encode>, decode = 0x805a53b <client_socket_decode>}, 
  {magic = 17582897398871087440, name = 0x8090577 "proxy", inst_size = 192, proto_config = 0x0, parse = 0x8058404 <common_socket_parse>, free = 0x805787c <common_socket_free>, recv = 0x805a168 <proxy_socket_recv>, send = 0x8058ec7 <proxy_socket_send>, print = 0x805792a <common_socket_print>, encode = 0x805a64b <proxy_socket_encode>, decode = 0x805a6fd <proxy_socket_decode>}, 
  {magic = 17582897398871087440, name = 0x809057d "auth", inst_size = 192, proto_config = 0x0, parse = 0x8058404 <common_socket_parse>, free = 0x805787c <common_socket_free>, recv = 0x805927c <auth_socket_recv>, send = 0x8058c9f <auth_socket_send>, print = 0x805792a <common_socket_print>, encode = 0x805a46e <client_socket_encode>, decode = 0x805a53b <client_socket_decode>}, 
  {magic = 17582897398871087440, name = 0x8090582 "acct", inst_size = 192, proto_config = 0x0, parse = 0x8058404 <common_socket_parse>, free = 0x805787c <common_socket_free>, recv = 0x805964c <acct_socket_recv>, send = 0x8058db3 <acct_socket_send>, print = 0x805792a <common_socket_print>, encode = 0x805a46e <client_socket_encode>, decode = 0x805a53b <client_socket_decode>}, 
  {magic = 17582897398871087440, name = 0x8090587 "detail", inst_size = 700, proto_config = 0x0, parse = 0x8085a6b <detail_parse>, free = 0x80855c5 <detail_free>, recv = 0x808461e <detail_recv>, send = 0x8083fe0 <detail_send>, print = 0x8085748 <detail_print>, encode = 0x808589d <detail_encode>, decode = 0x80858a7 <detail_decode>}, 
  {magic = 0, name = 0x809058e "vmps", inst_size = 0, proto_config = 0x0, parse = 0x0, free = 0x0, recv = 0x0, send = 0x0, print = 0x0, encode = 0x0, decode = 0x0}, 
  {magic = 0, name = 0x8090593 "dhcp", inst_size = 0, proto_config = 0x0, parse = 0x0, free = 0x0, recv = 0x0, send = 0x0, print = 0x0, encode = 0x0, decode = 0x0}, 
  {magic = 17582897398871087440, name = 0x8090598 "control", inst_size = 1396, proto_config = 0x0, parse = 0x805e012 <command_socket_parse>, free = 0x805dc3b <command_socket_free>, recv = 0x805ecc0 <command_domain_accept>, send = 0x805eff7 <command_domain_send>, print = 0x805e0d6 <command_socket_print>, encode = 0x805f001 <command_socket_encode>, decode = 0x805f00b <command_socket_decode>}, 
  {magic = 17582897398871087440, name = 0x80905a0 "coa", inst_size = 192, proto_config = 0x0, parse = 0x8058404 <common_socket_parse>, free = 0x0, recv = 0x8059d55 <coa_socket_recv>, send = 0x8058c9f <auth_socket_send>, print = 0x805792a <common_socket_print>, encode = 0x805a46e <client_socket_encode>, decode = 0x805a53b <client_socket_decode>}
} 
```

Looks like the lines with cmps and dhcp aren't correctly initialized.

**Comment by alandekok** [comment]
I've pushed a fix so that it doesn't crash.

The solution for 3.0.6 is to build && install it manually.  i.e. don't build debian packages.

If you do need debian packages, you will need to create a "freeradius-dhcp" package.
