### ISSUE TITLE
Crash with rlm_rest module and slow REST server.

### ISSUE THREAD

**Issue by lrstx** [FreeRADIUS/freeradius-server#922]
We encounter crashes of FreeRadius during load-tests. Our configuration includes a call to rlm_rest module in the post-proxy section. The remote REST server is under high load, and thus there are timeouts in the REST requests.

We're using FreeRADIUS v3.0.x branch, commit f4d1e488b182d005f9cd0c29f63c77feae6c8405.

Extract of the radius.log:

[...]
Tue Mar 10 10:17:58 2015 : ERROR: (1492) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1494) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1487) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1491) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1499) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1498) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1493) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1489) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1497) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1496) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1500) rlm_rest: ERROR: HTTP request error : Timeout was reached.
Tue Mar 10 10:17:58 2015 : ERROR: (1495) rlm_rest: ERROR: HTTP request error : Timeout was reached.
talloc: access after free error - first free may be at /home/admwpsrs/src/freeradius-server-3.0.x-c10/src/main/process.c:495

Bad talloc magic value - access after free

talloc abort: Bad talloc magic value - access after free

Backtrace:
#0  0x0000003535a0f3cb in raise () from /lib64/libpthread.so.0
#1  0x00007fbb48cb96c6 in skgesigOSCrash () from /opt/oracle/instantclient_11_2/libclntsh.so.11.1
#2  0x00007fbb48f6af79 in kpeDbgSignalHandler () from /opt/oracle/instantclient_11_2/libclntsh.so.11.1
#3  0x00007fbb48cb98d6 in skgesig_sigactionHandler () from /opt/oracle/instantclient_11_2/libclntsh.so.11.1
#4  <signal handler called>
#5  0x00000035352328a5 in raise () from /lib64/libc.so.6
#6  0x0000003535234085 in abort () from /lib64/libc.so.6
#7  0x00007fbb4a91d9ba in _fr_talloc_fault_simple (reason=<value optimized out>) at /home/admwpsrs/src/freeradius-server-3.0.x-c10/src/lib/debug.c:778
#8  0x00007fbb4a4f7179 in talloc_abort () from /opt/application/mwpsrs/products/talloc/2.1.0/lib/libtalloc.so.2
#9  0x00007fbb4a4f71f5 in talloc_abort_access_after_free () from /opt/application/mwpsrs/products/talloc/2.1.0/lib/libtalloc.so.2
#10 0x00007fbb4a4f7273 in talloc_chunk_from_ptr () from /opt/application/mwpsrs/products/talloc/2.1.0/lib/libtalloc.so.2
#11 0x00007fbb4a4f8e12 in talloc_get_name () from /opt/application/mwpsrs/products/talloc/2.1.0/lib/libtalloc.so.2
#12 0x00007fbb4a4f8f92 in _talloc_get_type_abort () from /opt/application/mwpsrs/products/talloc/2.1.0/lib/libtalloc.so.2
#13 0x000000000042cae7 in request_timer (ctx=<value optimized out>) at /home/admwpsrs/src/freeradius-server-3.0.x-c10/src/main/process.c:469
#14 0x00007fbb4a93876b in fr_event_run (el=0x1b20de0, when=<value optimized out>) at /home/admwpsrs/src/freeradius-server-3.0.x-c10/src/lib/event.c:310
#15 0x00007fbb4a938a4d in fr_event_loop (el=0x1b20de0) at /home/admwpsrs/src/freeradius-server-3.0.x-c10/src/lib/event.c:625
#16 0x000000000042598c in main (argc=3, argv=<value optimized out>) at /home/admwpsrs/src/freeradius-server-3.0.x-c10/src/main/radiusd.c:581

Regards,

**Comment by lrstx** [comment]
Not reproduced anymore with the latest HEAD (commit  40adcc0a2b0499b20ef3521ab5d87942a37ece66).

Thank you ! :+1:
